export const mockProducts = {
  data: {
    productos: [
      {
        id: 1,
        nombre: "Zanahoria",
        descripcion: "color naranja",
        imagen: "",
      },
      {
        id: 2,
        nombre: "Manzana",
        descripcion: "color roja",
        imagen: "",
      },
      {
        id: 3,
        nombre: "Pina",
        descripcion: "del caribe",
        imagen: "",
      },
      {
        id: 4,
        nombre: "Platano",
        descripcion: "verde",
        imagen: "",
      },
    ],
  },
  status: 200,
};

export const mockVehicleTypes = {
  data: {
    tipoTransportes: [
      {
        id: 1,
        descripcion: "Plataforma",
      },
      {
        id: 2,
        descripcion: "Tolva",
      },
      {
        id: 3,
        descripcion: "Furgón",
      },
      {
        id: 4,
        descripcion: "Baranda De Madera Alta",
      },
      {
        id: 5,
        descripcion: "Baranda De Madera Baja",
      },
      {
        id: 6,
        descripcion: "Baranda De Madera Estandar",
      },
      {
        id: 7,
        descripcion: "Baranda De Metal Alta",
      },

      {
        id: 8,
        descripcion: "Baranda De Metal Baja",
      },
      {
        id: 9,
        descripcion: "Baranda De Metal Rebatible",
      },
      {
        id: 10,
        descripcion: "Carrocería Especial Cisterna De Agua",
      },
      {
        id: 11,
        descripcion: "Carrocería Especial Cisterna De Combustible",
      },
      {
        id: 12,
        descripcion: "Compactador",
      },
    ],
  },
};

export const countries = [
  { code: "AD", label: "Andorra", phone: "376" },
  {
    code: "AE",
    label: "United Arab Emirates",
    phone: "971",
  },
  { code: "AF", label: "Afghanistan", phone: "93" },
  {
    code: "AG",
    label: "Antigua and Barbuda",
    phone: "1-268",
  },
  { code: "AI", label: "Anguilla", phone: "1-264" },
  { code: "AL", label: "Albania", phone: "355" },
  { code: "AM", label: "Armenia", phone: "374" },
  { code: "AO", label: "Angola", phone: "244" },
  { code: "AQ", label: "Antarctica", phone: "672" },
  { code: "AR", label: "Argentina", phone: "54" },
  { code: "AS", label: "American Samoa", phone: "1-684" },
  { code: "AT", label: "Austria", phone: "43" },
  {
    code: "AU",
    label: "Australia",
    phone: "61",
    suggested: true,
  },
  { code: "AW", label: "Aruba", phone: "297" },
  { code: "AX", label: "Alland Islands", phone: "358" },
  { code: "AZ", label: "Azerbaijan", phone: "994" },
  {
    code: "BA",
    label: "Bosnia and Herzegovina",
    phone: "387",
  },
  { code: "BB", label: "Barbados", phone: "1-246" },
  { code: "BD", label: "Bangladesh", phone: "880" },
  { code: "BE", label: "Belgium", phone: "32" },
  { code: "BF", label: "Burkina Faso", phone: "226" },
  { code: "BG", label: "Bulgaria", phone: "359" },
  { code: "BH", label: "Bahrain", phone: "973" },
  { code: "BI", label: "Burundi", phone: "257" },
  { code: "BJ", label: "Benin", phone: "229" },
  { code: "BL", label: "Saint Barthelemy", phone: "590" },
  { code: "BM", label: "Bermuda", phone: "1-441" },
  { code: "BN", label: "Brunei Darussalam", phone: "673" },
  { code: "BO", label: "Bolivia", phone: "591" },
  { code: "BR", label: "Brazil", phone: "55" },
  { code: "BS", label: "Bahamas", phone: "1-242" },
  { code: "BT", label: "Bhutan", phone: "975" },
  { code: "BV", label: "Bouvet Island", phone: "47" },
  { code: "BW", label: "Botswana", phone: "267" },
  { code: "BY", label: "Belarus", phone: "375" },
  { code: "BZ", label: "Belize", phone: "501" },
  {
    code: "CA",
    label: "Canada",
    phone: "1",
    suggested: true,
  },
  {
    code: "CC",
    label: "Cocos (Keeling) Islands",
    phone: "61",
  },
  {
    code: "CD",
    label: "Congo, Democratic Republic of the",
    phone: "243",
  },
  {
    code: "CF",
    label: "Central African Republic",
    phone: "236",
  },
  {
    code: "CG",
    label: "Congo, Republic of the",
    phone: "242",
  },
  { code: "CH", label: "Switzerland", phone: "41" },
  { code: "CI", label: "Cote d'Ivoire", phone: "225" },
  { code: "CK", label: "Cook Islands", phone: "682" },
  { code: "CL", label: "Chile", phone: "56" },
  { code: "CM", label: "Cameroon", phone: "237" },
  { code: "CN", label: "China", phone: "86" },
  { code: "CO", label: "Colombia", phone: "57" },
  { code: "CR", label: "Costa Rica", phone: "506" },
  { code: "CU", label: "Cuba", phone: "53" },
  { code: "CV", label: "Cape Verde", phone: "238" },
  { code: "CW", label: "Curacao", phone: "599" },
  { code: "CX", label: "Christmas Island", phone: "61" },
  { code: "CY", label: "Cyprus", phone: "357" },
  { code: "CZ", label: "Czech Republic", phone: "420" },
  {
    code: "DE",
    label: "Germany",
    phone: "49",
    suggested: true,
  },
  { code: "DJ", label: "Djibouti", phone: "253" },
  { code: "DK", label: "Denmark", phone: "45" },
  { code: "DM", label: "Dominica", phone: "1-767" },
  {
    code: "DO",
    label: "Dominican Republic",
    phone: "1-809",
  },
  { code: "DZ", label: "Algeria", phone: "213" },
  { code: "EC", label: "Ecuador", phone: "593" },
  { code: "EE", label: "Estonia", phone: "372" },
  { code: "EG", label: "Egypt", phone: "20" },
  { code: "EH", label: "Western Sahara", phone: "212" },
  { code: "ER", label: "Eritrea", phone: "291" },
  { code: "ES", label: "Spain", phone: "34" },
  { code: "ET", label: "Ethiopia", phone: "251" },
  { code: "FI", label: "Finland", phone: "358" },
  { code: "FJ", label: "Fiji", phone: "679" },
  {
    code: "FK",
    label: "Falkland Islands (Malvinas)",
    phone: "500",
  },
  {
    code: "FM",
    label: "Micronesia, Federated States of",
    phone: "691",
  },
  { code: "FO", label: "Faroe Islands", phone: "298" },
  {
    code: "FR",
    label: "France",
    phone: "33",
    suggested: true,
  },
  { code: "GA", label: "Gabon", phone: "241" },
  { code: "GB", label: "United Kingdom", phone: "44" },
  { code: "GD", label: "Grenada", phone: "1-473" },
  { code: "GE", label: "Georgia", phone: "995" },
  { code: "GF", label: "French Guiana", phone: "594" },
  { code: "GG", label: "Guernsey", phone: "44" },
  { code: "GH", label: "Ghana", phone: "233" },
  { code: "GI", label: "Gibraltar", phone: "350" },
  { code: "GL", label: "Greenland", phone: "299" },
  { code: "GM", label: "Gambia", phone: "220" },
  { code: "GN", label: "Guinea", phone: "224" },
  { code: "GP", label: "Guadeloupe", phone: "590" },
  { code: "GQ", label: "Equatorial Guinea", phone: "240" },
  { code: "GR", label: "Greece", phone: "30" },
  {
    code: "GS",
    label: "South Georgia and the South Sandwich Islands",
    phone: "500",
  },
  { code: "GT", label: "Guatemala", phone: "502" },
  { code: "GU", label: "Guam", phone: "1-671" },
  { code: "GW", label: "Guinea-Bissau", phone: "245" },
  { code: "GY", label: "Guyana", phone: "592" },
  { code: "HK", label: "Hong Kong", phone: "852" },
  {
    code: "HM",
    label: "Heard Island and McDonald Islands",
    phone: "672",
  },
  { code: "HN", label: "Honduras", phone: "504" },
  { code: "HR", label: "Croatia", phone: "385" },
  { code: "HT", label: "Haiti", phone: "509" },
  { code: "HU", label: "Hungary", phone: "36" },
  { code: "ID", label: "Indonesia", phone: "62" },
  { code: "IE", label: "Ireland", phone: "353" },
  { code: "IL", label: "Israel", phone: "972" },
  { code: "IM", label: "Isle of Man", phone: "44" },
  { code: "IN", label: "India", phone: "91" },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    phone: "246",
  },
  { code: "IQ", label: "Iraq", phone: "964" },
  {
    code: "IR",
    label: "Iran, Islamic Republic of",
    phone: "98",
  },
  { code: "IS", label: "Iceland", phone: "354" },
  { code: "IT", label: "Italy", phone: "39" },
  { code: "JE", label: "Jersey", phone: "44" },
  { code: "JM", label: "Jamaica", phone: "1-876" },
  { code: "JO", label: "Jordan", phone: "962" },
  {
    code: "JP",
    label: "Japan",
    phone: "81",
    suggested: true,
  },
  { code: "KE", label: "Kenya", phone: "254" },
  { code: "KG", label: "Kyrgyzstan", phone: "996" },
  { code: "KH", label: "Cambodia", phone: "855" },
  { code: "KI", label: "Kiribati", phone: "686" },
  { code: "KM", label: "Comoros", phone: "269" },
  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    phone: "1-869",
  },
  {
    code: "KP",
    label: "Korea, Democratic People's Republic of",
    phone: "850",
  },
  { code: "KR", label: "Korea, Republic of", phone: "82" },
  { code: "KW", label: "Kuwait", phone: "965" },
  { code: "KY", label: "Cayman Islands", phone: "1-345" },
  { code: "KZ", label: "Kazakhstan", phone: "7" },
  {
    code: "LA",
    label: "Lao People's Democratic Republic",
    phone: "856",
  },
  { code: "LB", label: "Lebanon", phone: "961" },
  { code: "LC", label: "Saint Lucia", phone: "1-758" },
  { code: "LI", label: "Liechtenstein", phone: "423" },
  { code: "LK", label: "Sri Lanka", phone: "94" },
  { code: "LR", label: "Liberia", phone: "231" },
  { code: "LS", label: "Lesotho", phone: "266" },
  { code: "LT", label: "Lithuania", phone: "370" },
  { code: "LU", label: "Luxembourg", phone: "352" },
  { code: "LV", label: "Latvia", phone: "371" },
  { code: "LY", label: "Libya", phone: "218" },
  { code: "MA", label: "Morocco", phone: "212" },
  { code: "MC", label: "Monaco", phone: "377" },
  {
    code: "MD",
    label: "Moldova, Republic of",
    phone: "373",
  },
  { code: "ME", label: "Montenegro", phone: "382" },
  {
    code: "MF",
    label: "Saint Martin (French part)",
    phone: "590",
  },
  { code: "MG", label: "Madagascar", phone: "261" },
  { code: "MH", label: "Marshall Islands", phone: "692" },
  {
    code: "MK",
    label: "Macedonia, the Former Yugoslav Republic of",
    phone: "389",
  },
  { code: "ML", label: "Mali", phone: "223" },
  { code: "MM", label: "Myanmar", phone: "95" },
  { code: "MN", label: "Mongolia", phone: "976" },
  { code: "MO", label: "Macao", phone: "853" },
  {
    code: "MP",
    label: "Northern Mariana Islands",
    phone: "1-670",
  },
  { code: "MQ", label: "Martinique", phone: "596" },
  { code: "MR", label: "Mauritania", phone: "222" },
  { code: "MS", label: "Montserrat", phone: "1-664" },
  { code: "MT", label: "Malta", phone: "356" },
  { code: "MU", label: "Mauritius", phone: "230" },
  { code: "MV", label: "Maldives", phone: "960" },
  { code: "MW", label: "Malawi", phone: "265" },
  { code: "MX", label: "Mexico", phone: "52" },
  { code: "MY", label: "Malaysia", phone: "60" },
  { code: "MZ", label: "Mozambique", phone: "258" },
  { code: "NA", label: "Namibia", phone: "264" },
  { code: "NC", label: "New Caledonia", phone: "687" },
  { code: "NE", label: "Niger", phone: "227" },
  { code: "NF", label: "Norfolk Island", phone: "672" },
  { code: "NG", label: "Nigeria", phone: "234" },
  { code: "NI", label: "Nicaragua", phone: "505" },
  { code: "NL", label: "Netherlands", phone: "31" },
  { code: "NO", label: "Norway", phone: "47" },
  { code: "NP", label: "Nepal", phone: "977" },
  { code: "NR", label: "Nauru", phone: "674" },
  { code: "NU", label: "Niue", phone: "683" },
  { code: "NZ", label: "New Zealand", phone: "64" },
  { code: "OM", label: "Oman", phone: "968" },
  { code: "PA", label: "Panama", phone: "507" },
  { code: "PE", label: "Peru", phone: "51" },
  { code: "PF", label: "French Polynesia", phone: "689" },
  { code: "PG", label: "Papua New Guinea", phone: "675" },
  { code: "PH", label: "Philippines", phone: "63" },
  { code: "PK", label: "Pakistan", phone: "92" },
  { code: "PL", label: "Poland", phone: "48" },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    phone: "508",
  },
  { code: "PN", label: "Pitcairn", phone: "870" },
  { code: "PR", label: "Puerto Rico", phone: "1" },
  {
    code: "PS",
    label: "Palestine, State of",
    phone: "970",
  },
  { code: "PT", label: "Portugal", phone: "351" },
  { code: "PW", label: "Palau", phone: "680" },
  { code: "PY", label: "Paraguay", phone: "595" },
  { code: "QA", label: "Qatar", phone: "974" },
  { code: "RE", label: "Reunion", phone: "262" },
  { code: "RO", label: "Romania", phone: "40" },
  { code: "RS", label: "Serbia", phone: "381" },
  { code: "RU", label: "Russian Federation", phone: "7" },
  { code: "RW", label: "Rwanda", phone: "250" },
  { code: "SA", label: "Saudi Arabia", phone: "966" },
  { code: "SB", label: "Solomon Islands", phone: "677" },
  { code: "SC", label: "Seychelles", phone: "248" },
  { code: "SD", label: "Sudan", phone: "249" },
  { code: "SE", label: "Sweden", phone: "46" },
  { code: "SG", label: "Singapore", phone: "65" },
  { code: "SH", label: "Saint Helena", phone: "290" },
  { code: "SI", label: "Slovenia", phone: "386" },
  {
    code: "SJ",
    label: "Svalbard and Jan Mayen",
    phone: "47",
  },
  { code: "SK", label: "Slovakia", phone: "421" },
  { code: "SL", label: "Sierra Leone", phone: "232" },
  { code: "SM", label: "San Marino", phone: "378" },
  { code: "SN", label: "Senegal", phone: "221" },
  { code: "SO", label: "Somalia", phone: "252" },
  { code: "SR", label: "Suriname", phone: "597" },
  { code: "SS", label: "South Sudan", phone: "211" },
  {
    code: "ST",
    label: "Sao Tome and Principe",
    phone: "239",
  },
  { code: "SV", label: "El Salvador", phone: "503" },
  {
    code: "SX",
    label: "Sint Maarten (Dutch part)",
    phone: "1-721",
  },
  {
    code: "SY",
    label: "Syrian Arab Republic",
    phone: "963",
  },
  { code: "SZ", label: "Swaziland", phone: "268" },
  {
    code: "TC",
    label: "Turks and Caicos Islands",
    phone: "1-649",
  },
  { code: "TD", label: "Chad", phone: "235" },
  {
    code: "TF",
    label: "French Southern Territories",
    phone: "262",
  },
  { code: "TG", label: "Togo", phone: "228" },
  { code: "TH", label: "Thailand", phone: "66" },
  { code: "TJ", label: "Tajikistan", phone: "992" },
  { code: "TK", label: "Tokelau", phone: "690" },
  { code: "TL", label: "Timor-Leste", phone: "670" },
  { code: "TM", label: "Turkmenistan", phone: "993" },
  { code: "TN", label: "Tunisia", phone: "216" },
  { code: "TO", label: "Tonga", phone: "676" },
  { code: "TR", label: "Turkey", phone: "90" },
  {
    code: "TT",
    label: "Trinidad and Tobago",
    phone: "1-868",
  },
  { code: "TV", label: "Tuvalu", phone: "688" },
  {
    code: "TW",
    label: "Taiwan, Republic of China",
    phone: "886",
  },
  {
    code: "TZ",
    label: "United Republic of Tanzania",
    phone: "255",
  },
  { code: "UA", label: "Ukraine", phone: "380" },
  { code: "UG", label: "Uganda", phone: "256" },
  {
    code: "US",
    label: "United States",
    phone: "1",
    suggested: true,
  },
  { code: "UY", label: "Uruguay", phone: "598" },
  { code: "UZ", label: "Uzbekistan", phone: "998" },
  {
    code: "VA",
    label: "Holy See (Vatican City State)",
    phone: "379",
  },
  {
    code: "VC",
    label: "Saint Vincent and the Grenadines",
    phone: "1-784",
  },
  { code: "VE", label: "Venezuela", phone: "58" },
  {
    code: "VG",
    label: "British Virgin Islands",
    phone: "1-284",
  },
  {
    code: "VI",
    label: "US Virgin Islands",
    phone: "1-340",
  },
  { code: "VN", label: "Vietnam", phone: "84" },
  { code: "VU", label: "Vanuatu", phone: "678" },
  { code: "WF", label: "Wallis and Futuna", phone: "681" },
  { code: "WS", label: "Samoa", phone: "685" },
  { code: "XK", label: "Kosovo", phone: "383" },
  { code: "YE", label: "Yemen", phone: "967" },
  { code: "YT", label: "Mayotte", phone: "262" },
  { code: "ZA", label: "South Africa", phone: "27" },
  { code: "ZM", label: "Zambia", phone: "260" },
  { code: "ZW", label: "Zimbabwe", phone: "263" },
];

export type Person = {
  firstName: string,
  lastName: string,
  age: number,
  gender: string,
  state: string,
  salary: number,
};

export const data: Person[] = [
  {
    firstName: "Danika",
    lastName: "Rodriguez",
    age: 57,
    gender: "Male",
    state: "Utah",
    salary: 31404,
  },
  {
    firstName: "Eloisa",
    lastName: "Kohler",
    age: 31,
    gender: "Male",
    state: "Alaska",
    salary: 45801,
  },
  {
    firstName: "Gunner",
    lastName: "Rolfson",
    age: 22,
    gender: "Male",
    state: "Arizona",
    salary: 54027,
  },
  {
    firstName: "Andreanne",
    lastName: "Hamill",
    age: 65,
    gender: "Female",
    state: "Hawaii",
    salary: 60975,
  },
  {
    firstName: "Kali",
    lastName: "Jones",
    age: 56,
    gender: "Female",
    state: "Kentucky",
    salary: 27067,
  },
  {
    firstName: "Felicia",
    lastName: "Mitchell",
    age: 34,
    gender: "Male",
    state: "South Carolina",
    salary: 48423,
  },
  {
    firstName: "Philip",
    lastName: "Koepp",
    age: 32,
    gender: "Male",
    state: "Louisiana",
    salary: 36713,
  },
  {
    firstName: "Aniya",
    lastName: "Mante",
    age: 41,
    gender: "Female",
    state: "Minnesota",
    salary: 77658,
  },
  {
    firstName: "Nelda",
    lastName: "Gottlieb",
    age: 41,
    gender: "Female",
    state: "Delaware",
    salary: 57634,
  },
  {
    firstName: "Marty",
    lastName: "Kihn",
    age: 19,
    gender: "Male",
    state: "Delaware",
    salary: 95427,
  },
  {
    firstName: "Alvis",
    lastName: "Turcotte",
    age: 53,
    gender: "Female",
    state: "Wyoming",
    salary: 14272,
  },
  {
    firstName: "Kavon",
    lastName: "Spencer",
    age: 37,
    gender: "Female",
    state: "Missouri",
    salary: 79499,
  },
  {
    firstName: "Winifred",
    lastName: "Wilderman",
    age: 56,
    gender: "Female",
    state: "Iowa",
    salary: 96293,
  },
  {
    firstName: "Brooklyn",
    lastName: "Monahan",
    age: 35,
    gender: "Female",
    state: "Nevada",
    salary: 13219,
  },
  {
    firstName: "Santino",
    lastName: "Brown",
    age: 33,
    gender: "Male",
    state: "Mississippi",
    salary: 36361,
  },
  {
    firstName: "Bianka",
    lastName: "Yost",
    age: 28,
    gender: "Female",
    state: "Wisconsin",
    salary: 89057,
  },
  {
    firstName: "Herman",
    lastName: "Herzog",
    age: 63,
    gender: "Female",
    state: "South Carolina",
    salary: 28110,
  },
  {
    firstName: "Earl",
    lastName: "Gottlieb",
    age: 65,
    gender: "Female",
    state: "Florida",
    salary: 31400,
  },
  {
    firstName: "Valentine",
    lastName: "Bauch",
    age: 61,
    gender: "Female",
    state: "North Carolina",
    salary: 35130,
  },
  {
    firstName: "Joanny",
    lastName: "Koss",
    age: 23,
    gender: "Male",
    state: "Colorado",
    salary: 90422,
  },
  {
    firstName: "Aliza",
    lastName: "Wilkinson",
    age: 25,
    gender: "Female",
    state: "Virginia",
    salary: 98417,
  },
  {
    firstName: "Eldred",
    lastName: "Collier",
    age: 37,
    gender: "Male",
    state: "Mississippi",
    salary: 43741,
  },
  {
    firstName: "Dorris",
    lastName: "Koch",
    age: 37,
    gender: "Male",
    state: "Delaware",
    salary: 40979,
  },
  {
    firstName: "Felix",
    lastName: "Zieme",
    age: 51,
    gender: "Male",
    state: "Ohio",
    salary: 55319,
  },
  {
    firstName: "Salma",
    lastName: "Treutel",
    age: 32,
    gender: "Female",
    state: "Pennsylvania",
    salary: 31722,
  },
  {
    firstName: "Durward",
    lastName: "Kris",
    age: 36,
    gender: "Male",
    state: "Iowa",
    salary: 28486,
  },
  {
    firstName: "Osborne",
    lastName: "Barrows",
    age: 28,
    gender: "Male",
    state: "West Virginia",
    salary: 43996,
  },
  {
    firstName: "Adelia",
    lastName: "Abbott",
    age: 38,
    gender: "Male",
    state: "Oregon",
    salary: 34720,
  },
  {
    firstName: "Thad",
    lastName: "Wiegand",
    age: 64,
    gender: "Female",
    state: "Alabama",
    salary: 56146,
  },
  {
    firstName: "Tiana",
    lastName: "Tromp",
    age: 51,
    gender: "Male",
    state: "Arkansas",
    salary: 45636,
  },
  {
    firstName: "Gwen",
    lastName: "Bergstrom",
    age: 36,
    gender: "Female",
    state: "Wyoming",
    salary: 95145,
  },
  {
    firstName: "Evalyn",
    lastName: "Mitchell",
    age: 53,
    gender: "Female",
    state: "Illinois",
    salary: 86990,
  },
  {
    firstName: "Edyth",
    lastName: "Macejkovic",
    age: 55,
    gender: "Female",
    state: "Kentucky",
    salary: 65344,
  },
  {
    firstName: "Lamar",
    lastName: "Bechtelar",
    age: 58,
    gender: "Female",
    state: "Rhode Island",
    salary: 93753,
  },
  {
    firstName: "Tillman",
    lastName: "Jacobs",
    age: 36,
    gender: "Female",
    state: "New Mexico",
    salary: 13393,
  },
  {
    firstName: "Turner",
    lastName: "Haley",
    age: 56,
    gender: "Female",
    state: "Nebraska",
    salary: 93733,
  },
  {
    firstName: "Omer",
    lastName: "Funk",
    age: 28,
    gender: "Female",
    state: "Iowa",
    salary: 77913,
  },
  {
    firstName: "Alivia",
    lastName: "Ledner",
    age: 56,
    gender: "Male",
    state: "Alabama",
    salary: 12591,
  },
  {
    firstName: "Dortha",
    lastName: "Schmitt",
    age: 43,
    gender: "Male",
    state: "Mississippi",
    salary: 80347,
  },
  {
    firstName: "Ellie",
    lastName: "Schinner",
    age: 41,
    gender: "Female",
    state: "Rhode Island",
    salary: 42232,
  },
  {
    firstName: "Pansy",
    lastName: "Reilly",
    age: 55,
    gender: "Male",
    state: "Louisiana",
    salary: 87255,
  },
  {
    firstName: "Alfonzo",
    lastName: "Abernathy",
    age: 40,
    gender: "Male",
    state: "Utah",
    salary: 53374,
  },
  {
    firstName: "Carmine",
    lastName: "Orn",
    age: 24,
    gender: "Female",
    state: "Georgia",
    salary: 89363,
  },
  {
    firstName: "Taylor",
    lastName: "Herzog",
    age: 63,
    gender: "Male",
    state: "Florida",
    salary: 81429,
  },
  {
    firstName: "Ray",
    lastName: "Little",
    age: 27,
    gender: "Female",
    state: "Maine",
    salary: 53736,
  },
  {
    firstName: "Melyssa",
    lastName: "Bechtelar",
    age: 56,
    gender: "Male",
    state: "New Mexico",
    salary: 85152,
  },
  {
    firstName: "Coy",
    lastName: "Schoen",
    age: 32,
    gender: "Male",
    state: "Florida",
    salary: 83999,
  },
  {
    firstName: "Lexi",
    lastName: "Reinger",
    age: 39,
    gender: "Female",
    state: "Virginia",
    salary: 17585,
  },
  {
    firstName: "Carlee",
    lastName: "Turcotte",
    age: 25,
    gender: "Male",
    state: "Missouri",
    salary: 85236,
  },
  {
    firstName: "Tamia",
    lastName: "Stamm",
    age: 47,
    gender: "Female",
    state: "Nevada",
    salary: 65037,
  },
  {
    firstName: "Leola",
    lastName: "Donnelly",
    age: 30,
    gender: "Female",
    state: "Missouri",
    salary: 23897,
  },
  {
    firstName: "Allison",
    lastName: "Stanton",
    age: 34,
    gender: "Male",
    state: "New Hampshire",
    salary: 34389,
  },
  {
    firstName: "Neoma",
    lastName: "Flatley",
    age: 65,
    gender: "Female",
    state: "Connecticut",
    salary: 43669,
  },
  {
    firstName: "Brad",
    lastName: "Altenwerth",
    age: 18,
    gender: "Male",
    state: "Virginia",
    salary: 85599,
  },
  {
    firstName: "Magdalen",
    lastName: "Berge",
    age: 58,
    gender: "Female",
    state: "Louisiana",
    salary: 65571,
  },
  {
    firstName: "Kathryn",
    lastName: "Kirlin",
    age: 48,
    gender: "Female",
    state: "New Hampshire",
    salary: 97434,
  },
  {
    firstName: "Rod",
    lastName: "Sawayn",
    age: 19,
    gender: "Female",
    state: "Nevada",
    salary: 58951,
  },
  {
    firstName: "Georgette",
    lastName: "Beatty",
    age: 53,
    gender: "Male",
    state: "Kentucky",
    salary: 12203,
  },
  {
    firstName: "Dianna",
    lastName: "King",
    age: 23,
    gender: "Female",
    state: "Vermont",
    salary: 13515,
  },
  {
    firstName: "Kellie",
    lastName: "Parker",
    age: 43,
    gender: "Trans Male",
    state: "Louisiana",
    salary: 49457,
  },
  {
    firstName: "Faustino",
    lastName: "Ankunding",
    age: 43,
    gender: "Male",
    state: "Indiana",
    salary: 49943,
  },
  {
    firstName: "Hilton",
    lastName: "Pacocha",
    age: 58,
    gender: "Male",
    state: "South Dakota",
    salary: 34874,
  },
  {
    firstName: "Shanel",
    lastName: "Schneider",
    age: 33,
    gender: "Female",
    state: "Nebraska",
    salary: 50446,
  },
  {
    firstName: "Wade",
    lastName: "Kiehn",
    age: 23,
    gender: "Male",
    state: "Delaware",
    salary: 29522,
  },
  {
    firstName: "Austyn",
    lastName: "Rempel",
    age: 35,
    gender: "Female",
    state: "Arkansas",
    salary: 42997,
  },
  {
    firstName: "Maggie",
    lastName: "Keebler",
    age: 20,
    gender: "Female",
    state: "California",
    salary: 11588,
  },
  {
    firstName: "Ruby",
    lastName: "Kertzmann",
    age: 40,
    gender: "Female",
    state: "Missouri",
    salary: 45860,
  },
  {
    firstName: "Lilyan",
    lastName: "Pfannerstill",
    age: 37,
    gender: "Cisgender",
    state: "Washington",
    salary: 37347,
  },
  {
    firstName: "Fletcher",
    lastName: "Huels",
    age: 65,
    gender: "Female",
    state: "Colorado",
    salary: 11596,
  },
  {
    firstName: "Danyka",
    lastName: "Gleason",
    age: 36,
    gender: "Male",
    state: "Alabama",
    salary: 71238,
  },
  {
    firstName: "Tressa",
    lastName: "McCullough",
    age: 64,
    gender: "Female",
    state: "Virginia",
    salary: 47028,
  },
  {
    firstName: "Heber",
    lastName: "Bernhard",
    age: 37,
    gender: "Cisgender",
    state: "California",
    salary: 11268,
  },
  {
    firstName: "Damon",
    lastName: "Barrows",
    age: 20,
    gender: "Female",
    state: "West Virginia",
    salary: 22796,
  },
  {
    firstName: "Willy",
    lastName: "Koss",
    age: 35,
    gender: "Female",
    state: "Colorado",
    salary: 88346,
  },
  {
    firstName: "Carley",
    lastName: "Block",
    age: 54,
    gender: "Female",
    state: "Michigan",
    salary: 32934,
  },
  {
    firstName: "Randy",
    lastName: "Powlowski",
    age: 31,
    gender: "Female",
    state: "Mississippi",
    salary: 68186,
  },
  {
    firstName: "Rubye",
    lastName: "Weissnat",
    age: 43,
    gender: "Female",
    state: "South Carolina",
    salary: 19377,
  },
  {
    firstName: "Gloria",
    lastName: "Green",
    age: 54,
    gender: "Male",
    state: "Georgia",
    salary: 85559,
  },
  {
    firstName: "Kian",
    lastName: "Hand",
    age: 56,
    gender: "Male",
    state: "Alaska",
    salary: 81062,
  },
  {
    firstName: "Adelia",
    lastName: "Weber",
    age: 29,
    gender: "Male",
    state: "Wyoming",
    salary: 62704,
  },
  {
    firstName: "Clemmie",
    lastName: "Nienow",
    age: 64,
    gender: "Male",
    state: "New Hampshire",
    salary: 84951,
  },
  {
    firstName: "Buck",
    lastName: "Ankunding",
    age: 25,
    gender: "Male",
    state: "Kentucky",
    salary: 88189,
  },
  {
    firstName: "Abbey",
    lastName: "Kulas",
    age: 36,
    gender: "Female",
    state: "Oklahoma",
    salary: 62902,
  },
  {
    firstName: "Godfrey",
    lastName: "Beahan",
    age: 43,
    gender: "Female",
    state: "Georgia",
    salary: 85231,
  },
  {
    firstName: "Jayde",
    lastName: "Friesen",
    age: 60,
    gender: "Male",
    state: "Minnesota",
    salary: 68939,
  },
  {
    firstName: "Kaela",
    lastName: "Bernhard",
    age: 51,
    gender: "Female",
    state: "Virginia",
    salary: 61567,
  },
  {
    firstName: "Jerome",
    lastName: "Jast",
    age: 22,
    gender: "Male",
    state: "Wisconsin",
    salary: 47210,
  },
  {
    firstName: "Lawrence",
    lastName: "Steuber",
    age: 39,
    gender: "Male",
    state: "Mississippi",
    salary: 99291,
  },
  {
    firstName: "Deon",
    lastName: "Romaguera",
    age: 53,
    gender: "Female",
    state: "Vermont",
    salary: 98288,
  },
  {
    firstName: "Jena",
    lastName: "O'Hara",
    age: 41,
    gender: "Female",
    state: "Iowa",
    salary: 40063,
  },
  {
    firstName: "Ima",
    lastName: "Bartell",
    age: 62,
    gender: "Female",
    state: "Rhode Island",
    salary: 72570,
  },
  {
    firstName: "Antonina",
    lastName: "McCullough",
    age: 59,
    gender: "Male",
    state: "Nebraska",
    salary: 95189,
  },
  {
    firstName: "Steve",
    lastName: "Gislason",
    age: 41,
    gender: "Male",
    state: "Kentucky",
    salary: 93162,
  },
  {
    firstName: "Carmela",
    lastName: "Boyle",
    age: 49,
    gender: "Male",
    state: "Virginia",
    salary: 71890,
  },
  {
    firstName: "Horacio",
    lastName: "Murphy",
    age: 51,
    gender: "Female",
    state: "Vermont",
    salary: 32343,
  },
  {
    firstName: "Bettie",
    lastName: "O'Hara",
    age: 40,
    gender: "Female",
    state: "North Dakota",
    salary: 60492,
  },
  {
    firstName: "Rene",
    lastName: "Gottlieb",
    age: 34,
    gender: "Female",
    state: "Florida",
    salary: 90192,
  },
  {
    firstName: "Turner",
    lastName: "Ward",
    age: 32,
    gender: "Female",
    state: "Tennessee",
    salary: 55249,
  },
  {
    firstName: "Elaina",
    lastName: "Orn",
    age: 30,
    gender: "Female",
    state: "Michigan",
    salary: 72501,
  },
  {
    firstName: "Nayeli",
    lastName: "Littel",
    age: 44,
    gender: "Nonbinary",
    state: "Maine",
    salary: 53740,
  },
  {
    firstName: "Velda",
    lastName: "Kuphal",
    age: 57,
    gender: "Male",
    state: "New York",
    salary: 93481,
  },
  {
    firstName: "Loyce",
    lastName: "Schmidt",
    age: 29,
    gender: "Female",
    state: "Alaska",
    salary: 76295,
  },
  {
    firstName: "Oswaldo",
    lastName: "DuBuque",
    age: 30,
    gender: "Male",
    state: "Ohio",
    salary: 55034,
  },
  {
    firstName: "Kiarra",
    lastName: "Dooley",
    age: 20,
    gender: "Male",
    state: "Nebraska",
    salary: 60415,
  },
  {
    firstName: "Ashleigh",
    lastName: "Fahey",
    age: 56,
    gender: "Female",
    state: "New Mexico",
    salary: 28186,
  },
  {
    firstName: "Jordyn",
    lastName: "Weissnat",
    age: 49,
    gender: "Female",
    state: "North Dakota",
    salary: 81663,
  },
  {
    firstName: "Maureen",
    lastName: "Swift",
    age: 63,
    gender: "Male",
    state: "Ohio",
    salary: 53538,
  },
  {
    firstName: "Cathryn",
    lastName: "Spinka",
    age: 42,
    gender: "Female",
    state: "New Hampshire",
    salary: 14586,
  },
  {
    firstName: "Xzavier",
    lastName: "Raynor",
    age: 37,
    gender: "Male",
    state: "California",
    salary: 60776,
  },
  {
    firstName: "Alexander",
    lastName: "Kris",
    age: 63,
    gender: "Female",
    state: "North Carolina",
    salary: 85926,
  },
  {
    firstName: "Golda",
    lastName: "McLaughlin",
    age: 41,
    gender: "Cisgender",
    state: "Kansas",
    salary: 49250,
  },
  {
    firstName: "Delbert",
    lastName: "Jacobson",
    age: 40,
    gender: "Female",
    state: "New Hampshire",
    salary: 58482,
  },
  {
    firstName: "Cordia",
    lastName: "Hermann",
    age: 45,
    gender: "Female",
    state: "Mississippi",
    salary: 29543,
  },
  {
    firstName: "Brennon",
    lastName: "Smith",
    age: 39,
    gender: "Nonbinary",
    state: "Missouri",
    salary: 65193,
  },
  {
    firstName: "Kraig",
    lastName: "Moen",
    age: 59,
    gender: "Male",
    state: "West Virginia",
    salary: 52677,
  },
  {
    firstName: "Lionel",
    lastName: "Hartmann",
    age: 30,
    gender: "Nonbinary",
    state: "Alabama",
    salary: 58743,
  },
  {
    firstName: "Terrill",
    lastName: "Feest",
    age: 61,
    gender: "Female",
    state: "West Virginia",
    salary: 97637,
  },
  {
    firstName: "Jaylin",
    lastName: "Murazik",
    age: 56,
    gender: "Male",
    state: "Wyoming",
    salary: 68290,
  },
  {
    firstName: "Tyrique",
    lastName: "Emard",
    age: 55,
    gender: "Male",
    state: "New Hampshire",
    salary: 23052,
  },
  {
    firstName: "Shanelle",
    lastName: "Hilll",
    age: 35,
    gender: "Male",
    state: "New Mexico",
    salary: 66504,
  },
  {
    firstName: "Antwan",
    lastName: "Zieme",
    age: 21,
    gender: "Male",
    state: "Utah",
    salary: 56638,
  },
  {
    firstName: "Kyler",
    lastName: "Schmeler",
    age: 19,
    gender: "Female",
    state: "Oklahoma",
    salary: 73721,
  },
  {
    firstName: "Colt",
    lastName: "Wiegand",
    age: 64,
    gender: "Male",
    state: "New York",
    salary: 69024,
  },
  {
    firstName: "Paul",
    lastName: "Leannon",
    age: 21,
    gender: "Male",
    state: "New York",
    salary: 67575,
  },
  {
    firstName: "Magnus",
    lastName: "Ortiz",
    age: 53,
    gender: "Female",
    state: "Ohio",
    salary: 18489,
  },
  {
    firstName: "Kathryn",
    lastName: "Langworth",
    age: 39,
    gender: "Male",
    state: "Utah",
    salary: 25720,
  },
  {
    firstName: "Zelma",
    lastName: "Grimes",
    age: 42,
    gender: "Male",
    state: "Texas",
    salary: 94083,
  },
  {
    firstName: "Eddie",
    lastName: "Paucek",
    age: 40,
    gender: "Nonbinary",
    state: "Michigan",
    salary: 96538,
  },
  {
    firstName: "Tressa",
    lastName: "Cartwright",
    age: 26,
    gender: "Female",
    state: "Maine",
    salary: 38495,
  },
  {
    firstName: "Dawn",
    lastName: "Huels",
    age: 57,
    gender: "Male",
    state: "New Jersey",
    salary: 41603,
  },
  {
    firstName: "Pinkie",
    lastName: "Rau",
    age: 30,
    gender: "Female",
    state: "New Jersey",
    salary: 27073,
  },
  {
    firstName: "Macie",
    lastName: "Reynolds",
    age: 18,
    gender: "Male",
    state: "Massachusetts",
    salary: 86581,
  },
  {
    firstName: "Bertrand",
    lastName: "Cummings",
    age: 62,
    gender: "Female",
    state: "Illinois",
    salary: 96908,
  },
  {
    firstName: "Dylan",
    lastName: "Wolf",
    age: 65,
    gender: "Male",
    state: "New York",
    salary: 75557,
  },
  {
    firstName: "Elsa",
    lastName: "Lockman",
    age: 36,
    gender: "Female",
    state: "Colorado",
    salary: 30586,
  },
  {
    firstName: "Haylee",
    lastName: "Price",
    age: 57,
    gender: "Male",
    state: "Utah",
    salary: 59047,
  },
  {
    firstName: "Harold",
    lastName: "Stracke",
    age: 49,
    gender: "Female",
    state: "Indiana",
    salary: 99744,
  },
  {
    firstName: "Kelly",
    lastName: "Monahan",
    age: 20,
    gender: "Male",
    state: "Indiana",
    salary: 64408,
  },
  {
    firstName: "Lee",
    lastName: "O'Hara",
    age: 38,
    gender: "Male",
    state: "Washington",
    salary: 23136,
  },
  {
    firstName: "Trevor",
    lastName: "Beier",
    age: 65,
    gender: "Female",
    state: "New York",
    salary: 19235,
  },
  {
    firstName: "Theron",
    lastName: "Windler",
    age: 32,
    gender: "Male",
    state: "North Dakota",
    salary: 52825,
  },
  {
    firstName: "Jennings",
    lastName: "Halvorson",
    age: 34,
    gender: "Male",
    state: "New York",
    salary: 24737,
  },
  {
    firstName: "Charity",
    lastName: "Kuvalis",
    age: 40,
    gender: "Male",
    state: "Mississippi",
    salary: 60813,
  },
  {
    firstName: "Kaitlyn",
    lastName: "Maggio",
    age: 23,
    gender: "Female",
    state: "Indiana",
    salary: 74616,
  },
  {
    firstName: "Reymundo",
    lastName: "Osinski",
    age: 45,
    gender: "Female",
    state: "New Mexico",
    salary: 50978,
  },
  {
    firstName: "Glen",
    lastName: "Kub",
    age: 47,
    gender: "Male",
    state: "Vermont",
    salary: 85742,
  },
  {
    firstName: "Reinhold",
    lastName: "Reichel",
    age: 30,
    gender: "Female",
    state: "Alabama",
    salary: 30531,
  },
  {
    firstName: "Theresia",
    lastName: "Wyman",
    age: 50,
    gender: "Female",
    state: "Kentucky",
    salary: 49835,
  },
  {
    firstName: "Lurline",
    lastName: "Koepp",
    age: 59,
    gender: "Female",
    state: "Alabama",
    salary: 10645,
  },
  {
    firstName: "Elise",
    lastName: "Schimmel",
    age: 42,
    gender: "Male",
    state: "Illinois",
    salary: 80267,
  },
  {
    firstName: "Maeve",
    lastName: "Mante",
    age: 54,
    gender: "Male",
    state: "Massachusetts",
    salary: 34713,
  },
  {
    firstName: "Michale",
    lastName: "Collier",
    age: 59,
    gender: "Male",
    state: "Alaska",
    salary: 75197,
  },
  {
    firstName: "Adell",
    lastName: "Champlin",
    age: 37,
    gender: "Female",
    state: "Tennessee",
    salary: 80245,
  },
  {
    firstName: "Cyril",
    lastName: "Hahn",
    age: 48,
    gender: "Male",
    state: "Louisiana",
    salary: 76679,
  },
  {
    firstName: "Josiah",
    lastName: "Durgan",
    age: 50,
    gender: "Female",
    state: "North Carolina",
    salary: 76309,
  },
  {
    firstName: "Rene",
    lastName: "Weber",
    age: 58,
    gender: "Female",
    state: "Mississippi",
    salary: 51097,
  },
  {
    firstName: "Stacey",
    lastName: "Pouros",
    age: 34,
    gender: "Male",
    state: "Minnesota",
    salary: 71566,
  },
  {
    firstName: "Kody",
    lastName: "Braun",
    age: 38,
    gender: "Female",
    state: "Alabama",
    salary: 63733,
  },
  {
    firstName: "Maritza",
    lastName: "Bartell",
    age: 45,
    gender: "Female",
    state: "Idaho",
    salary: 14581,
  },
  {
    firstName: "Abbey",
    lastName: "Fay",
    age: 30,
    gender: "Male",
    state: "New Mexico",
    salary: 21372,
  },
  {
    firstName: "Duncan",
    lastName: "Carroll",
    age: 50,
    gender: "Male",
    state: "Washington",
    salary: 65996,
  },
  {
    firstName: "Eldridge",
    lastName: "Stroman",
    age: 42,
    gender: "Male",
    state: "Alaska",
    salary: 59594,
  },
  {
    firstName: "Roberta",
    lastName: "Bashirian",
    age: 38,
    gender: "Male",
    state: "Nevada",
    salary: 91870,
  },
  {
    firstName: "Erwin",
    lastName: "Kihn",
    age: 26,
    gender: "Nonbinary",
    state: "Louisiana",
    salary: 48803,
  },
  {
    firstName: "Alberta",
    lastName: "Considine",
    age: 37,
    gender: "Male",
    state: "Illinois",
    salary: 84906,
  },
  {
    firstName: "Lexi",
    lastName: "O'Hara",
    age: 29,
    gender: "Male",
    state: "Virginia",
    salary: 72684,
  },
  {
    firstName: "Alvera",
    lastName: "Balistreri",
    age: 25,
    gender: "Female",
    state: "Alaska",
    salary: 79844,
  },
  {
    firstName: "Kayden",
    lastName: "Emard",
    age: 35,
    gender: "Female",
    state: "Alaska",
    salary: 98252,
  },
  {
    firstName: "Rahul",
    lastName: "Greenfelder",
    age: 27,
    gender: "Female",
    state: "Wisconsin",
    salary: 63419,
  },
  {
    firstName: "Caterina",
    lastName: "Koss",
    age: 52,
    gender: "Male",
    state: "Arkansas",
    salary: 58259,
  },
  {
    firstName: "Eriberto",
    lastName: "Klein",
    age: 20,
    gender: "Male",
    state: "Iowa",
    salary: 73198,
  },
  {
    firstName: "Lilla",
    lastName: "Thompson",
    age: 36,
    gender: "Male",
    state: "Washington",
    salary: 53856,
  },
  {
    firstName: "Jonathan",
    lastName: "Brakus",
    age: 47,
    gender: "Female",
    state: "Kansas",
    salary: 45726,
  },
  {
    firstName: "Darby",
    lastName: "Frami",
    age: 58,
    gender: "Female",
    state: "Texas",
    salary: 68700,
  },
  {
    firstName: "Damon",
    lastName: "Barrows",
    age: 22,
    gender: "Female",
    state: "Pennsylvania",
    salary: 23156,
  },
  {
    firstName: "Eliezer",
    lastName: "Erdman",
    age: 25,
    gender: "Female",
    state: "Missouri",
    salary: 48537,
  },
  {
    firstName: "Marge",
    lastName: "Windler",
    age: 29,
    gender: "Female",
    state: "Georgia",
    salary: 54107,
  },
  {
    firstName: "Raleigh",
    lastName: "Lakin",
    age: 48,
    gender: "Male",
    state: "Nebraska",
    salary: 13802,
  },
  {
    firstName: "Freida",
    lastName: "Barrows",
    age: 54,
    gender: "Female",
    state: "North Carolina",
    salary: 32719,
  },
  {
    firstName: "Allen",
    lastName: "Gaylord",
    age: 57,
    gender: "Female",
    state: "Virginia",
    salary: 41416,
  },
  {
    firstName: "Blanche",
    lastName: "Luettgen",
    age: 39,
    gender: "Male",
    state: "Missouri",
    salary: 81498,
  },
  {
    firstName: "Domingo",
    lastName: "Bauch",
    age: 36,
    gender: "Female",
    state: "Alaska",
    salary: 35159,
  },
  {
    firstName: "Elijah",
    lastName: "Kiehn",
    age: 43,
    gender: "Female",
    state: "Colorado",
    salary: 11772,
  },
  {
    firstName: "Mozelle",
    lastName: "Kuvalis",
    age: 44,
    gender: "Female",
    state: "Massachusetts",
    salary: 25499,
  },
  {
    firstName: "Adaline",
    lastName: "Volkman",
    age: 19,
    gender: "Female",
    state: "Louisiana",
    salary: 74049,
  },
  {
    firstName: "Edward",
    lastName: "Wisozk",
    age: 22,
    gender: "Female",
    state: "Washington",
    salary: 90236,
  },
  {
    firstName: "Rita",
    lastName: "Gaylord",
    age: 64,
    gender: "Female",
    state: "Georgia",
    salary: 12755,
  },
  {
    firstName: "Burdette",
    lastName: "Fisher",
    age: 27,
    gender: "Female",
    state: "Connecticut",
    salary: 29371,
  },
  {
    firstName: "Naomi",
    lastName: "Ebert",
    age: 52,
    gender: "Female",
    state: "Colorado",
    salary: 48525,
  },
  {
    firstName: "Sid",
    lastName: "Champlin",
    age: 43,
    gender: "Female",
    state: "Pennsylvania",
    salary: 77186,
  },
  {
    firstName: "Darwin",
    lastName: "Luettgen",
    age: 57,
    gender: "Male",
    state: "Illinois",
    salary: 34401,
  },
  {
    firstName: "Bonita",
    lastName: "Klocko",
    age: 43,
    gender: "Male",
    state: "Arkansas",
    salary: 85883,
  },
  {
    firstName: "Tremayne",
    lastName: "Casper",
    age: 58,
    gender: "Female",
    state: "Nebraska",
    salary: 47237,
  },
  {
    firstName: "Maximillian",
    lastName: "O'Connell",
    age: 27,
    gender: "Female",
    state: "New Jersey",
    salary: 33190,
  },
  {
    firstName: "Nola",
    lastName: "Bashirian",
    age: 36,
    gender: "Male",
    state: "Nebraska",
    salary: 45510,
  },
  {
    firstName: "Vernon",
    lastName: "Murray",
    age: 62,
    gender: "Male",
    state: "Montana",
    salary: 25464,
  },
  {
    firstName: "Edwin",
    lastName: "Rippin",
    age: 32,
    gender: "Male",
    state: "Michigan",
    salary: 44083,
  },
  {
    firstName: "Zola",
    lastName: "Goodwin",
    age: 20,
    gender: "Male",
    state: "Idaho",
    salary: 62729,
  },
  {
    firstName: "Dangelo",
    lastName: "Abshire",
    age: 31,
    gender: "Female",
    state: "Connecticut",
    salary: 40247,
  },
  {
    firstName: "Kallie",
    lastName: "Swaniawski",
    age: 45,
    gender: "Male",
    state: "Virginia",
    salary: 35294,
  },
];
